django_project/urls.py
from pathlib import Path

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.db.utils import OperationalError
from django.urls import include, path
from django.views.generic import TemplateView

from prod.models import Prod

from .api import api

try:
    last_prod = Prod.objects.last()
except OperationalError:
    last_prod = None

urlpatterns = [
    path(
        "",
        TemplateView.as_view(template_name="home.html"),
        kwargs={
            "last_prod": last_prod,
            "header_title": "儀表板",
            "header_description": "歡迎使用本系統。",
        },
        name="home",
    ),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("prod.urls")),
    path("", include("order.urls")),
    path("", include("manufacturer.urls")),
    # reloader
    # path("__reload__/", include("django_browser_reload.urls")),
    # debug
    path("__debug__/", include("debug_toolbar.urls")),
    # ninja api
    path("api/", api.urls),
]

# performance profiling
# urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prod/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from .views import (
    CateAutocomplete,
    ProdAutocomplete,
    ProdCategoryAutocomplete,
    ProdCreateMultipleView,
    ProdCreateView,
    ProdDashboardView,
    ProdDeleteView,
    ProdDetailView,
    ProdListView,
    ProdUpdateMultipleView,
    ProdUpdateView,
    SubCateAutocomplete,
    SubSubCateAutocomplete,
)

urlpatterns = [
    path("prods/", ProdListView.as_view(), name="prod_list"),
    path("prods/create/", ProdCreateView.as_view(), name="prod_create"),
    path("prods/<int:pk>/", ProdDetailView.as_view(), name="prod_detail"),
    path("prods/<int:pk>/update/", ProdUpdateView.as_view(), name="prod_update"),
    path("prods/<int:pk>/delete/", ProdDeleteView.as_view(), name="prod_delete"),
    # with ajax
    path(
        "prods/create_multiple/",
        ProdCreateMultipleView.as_view(),
        name="prod_create_multiple",
    ),
    path(
        "prods/update_multiple/",
        ProdUpdateMultipleView.as_view(),
        name="prod_update_multiple",
    ),
    # d3.js
    path(
        "prods/dashboard/",
        ProdDashboardView.as_view(),
        name="prod_dashboard",
    ),
    # autocomplete
    path(
        "prod_cate/all/autocomplete/",
        ProdCategoryAutocomplete.as_view(),
        name="prod_all_cate_autocomplete",
    ),
    path(
        "prod_cate/cate/autocomplete",
        CateAutocomplete.as_view(),
        name="prod_cate_autocomplete",
    ),
    path(
        "prod_cate/subcate/autocomplete",
        SubCateAutocomplete.as_view(),
        name="prod_subcate_autocomplete",
    ),
    path(
        "prod_cate/subsubcate/autocomplete",
        SubSubCateAutocomplete.as_view(),
        name="prod_subsubcate_autocomplete",
    ),
    path("prod/autocomplete/", ProdAutocomplete.as_view(), name="prod_autocomplete"),
]

prod/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Case, F, Value, When
from django.db.models.functions import Concat, Substr
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from manufacturer.models import Manufacturer


class CateTypeChoices(models.IntegerChoices):
    Cate = 1, _("大分類")
    SubCate = 2, _("中分類")
    SubSubCate = 3, _("小分類")


class ProdCategory(models.Model):

    cate_no = models.CharField(
        primary_key=True,
        verbose_name=_("分類編號"),
        max_length=6,
        validators=[
            RegexValidator(r"^\d{6}$", message=_("您必須輸入一個 6 位數的分類編號。"))
        ],
    )
    cate_name = models.CharField(verbose_name=_("分類名稱"), max_length=255)
    cate_type = models.PositiveSmallIntegerField(
        verbose_name=_("分類大小"),
        choices=CateTypeChoices,
        default=CateTypeChoices.Cate,
    )
    cate_cate_no = models.GeneratedField(
        verbose_name=_("分類大類編號"),
        expression=Case(
            When(cate_type=CateTypeChoices.Cate, then=F("cate_no")),
            When(
                cate_type=CateTypeChoices.SubCate,
                then=Concat(
                    Value("0000"),
                    Substr("cate_no", 3, 2),
                    output_field=models.CharField(max_length=6),
                ),
            ),
            default=Concat(
                Value("0000"),
                Substr("cate_no", 1, 2),
                output_field=models.CharField(max_length=6),
            ),
        ),
        output_field=models.CharField(max_length=6),
        db_persist=True,
        null=True,
    )

    cate_subcate_no = models.GeneratedField(
        verbose_name=_("分類中類編號"),
        expression=Case(
            When(
                cate_type=CateTypeChoices.SubSubCate,
                then=Concat(
                    Value("00"),
                    Substr("cate_no", 1, 4),
                    output_field=models.CharField(max_length=6),
                ),
            ),
            When(
                cate_type=CateTypeChoices.SubCate,
                then=F("cate_no"),
            ),
            default=None,
        ),
        output_field=models.CharField(max_length=6),
        db_persist=True,
        null=True,
    )

    cate_parent_no = models.GeneratedField(
        verbose_name=_("分類上層編號"),
        expression=Case(
            When(cate_type=CateTypeChoices.Cate, then=None),
            When(
                cate_type=CateTypeChoices.SubCate,
                then=Concat(
                    Value("0000"),
                    Substr("cate_no", 3, 2),
                    output_field=models.CharField(max_length=6),
                ),
            ),
            default=Concat(
                Value("00"),
                Substr("cate_no", 1, 4),
                output_field=models.CharField(max_length=6),
            ),
        ),
        output_field=models.CharField(max_length=6),
        db_persist=True,
        null=True,
    )

    def __str__(self) -> str:
        return self.cate_no + " - " + self.cate_name

    class Meta:
        ordering = ["cate_no"]


class SalesStatusChoices(models.IntegerChoices):
    ABNORMAL = 0, _("異常 (因為商品品質異常暫時停止銷售)")
    NORMAL = 1, _("正常")


class QualityAssuranceStatusChoices(models.IntegerChoices):
    NORMAL = 1, _("正常追蹤")
    NEW_PROD = 2, _("新產品追蹤")
    CASE = 3, _("案例追蹤")
    LICENSE = 4, _("證照追蹤")


class UnitChoices(models.IntegerChoices):
    INDIVIDUAL = 1, _("個")
    PIECE1 = 2, _("條")
    UNIT = 3, _("台")
    BOTTLE = 4, _("瓶")
    SET = 5, _("組")
    KIT = 6, _("套")
    PACK = 7, _("打")
    BAG1 = 8, _("包")
    BOX = 9, _("盒")
    CAN = 10, _("罐")
    BLOCK = 11, _("塊")
    ITEM = 12, _("件")
    SINGLE = 13, _("只")
    PORTION = 14, _("份")
    PIECE2 = 15, _("片")
    BUCKET = 16, _("桶")
    STICK = 17, _("支")
    CUP = 18, _("杯")
    PAIR = 19, _("雙")
    SHEET = 20, _("張")
    CARD = 21, _("卡")
    STRING = 22, _("串")
    BOOK = 23, _("本")
    ROLL1 = 24, _("捲")
    ROLL2 = 25, _("卷")
    CASE = 31, _("箱")
    BOWL = 55, _("碗")
    TOP = 60, _("頂")
    BAG2 = 61, _("袋")


class SellZoneChoices(models.TextChoices):
    COSMED_PHYSICAL = "1", _("康是美實體")
    COSMED_EC = "2", _("康是美EC")
    COSMED_PHYSICAL_EC = "3", _("康是美實體+EC")
    UNIKCY_PHYSICAL = "4", _("UNIKCY 實體")
    UNIKCY_EC = "5", _("UNIKCY EC")
    UNIKCY_PHYSICAL_EC = "6", _("UNIKCY 實體+EC")
    COSMED_PHYSICAL_UNIKCY_PHYSICAL = "7", _("康是美實體 / UNIKCY 實體")
    COSMED_PHYSICAL_UNIKCY_EC = "8", _("康是美實體 / UNIKCY EC")
    COSMED_PHYSICAL_UNIKCY_PHYSICAL_EC = "9", _("康是美實體 / UNIKCY 實體+EC")
    COSMED_EC_UNIKCY_PHYSICAL = "A", _("康是美EC / UNIKCY 實體")
    COSMED_EC_UNIKCY_EC = "B", _("康是美EC / UNIKCY EC")
    COSMED_EC_UNIKCY_PHYSICAL_EC = "C", _("康是美EC / UNIKCY 實體+EC")
    COSMED_PHYSICAL_EC_UNIKCY_PHYSICAL = "D", _("康是美實體+EC / UNIKCY 實體")
    COSMED_PHYSICAL_EC_UNIKCY_EC = "E", _("康是美實體+EC / UNIKCY EC")
    COSMED_PHYSICAL_EC_UNIKCY_PHYSICAL_EC = "F", _("康是美實體+EC / UNIKCY 實體+EC")


class Prod(models.Model):
    prod_no = models.BigAutoField(primary_key=True, verbose_name=_("商品編號"))
    prod_name = models.CharField(verbose_name=_("商品名稱"), max_length=255)
    prod_desc = models.TextField(
        verbose_name=_("商品描述"), null=True, default=None, blank=True
    )
    prod_img = models.ImageField(
        upload_to="images/",
        verbose_name=_("商品圖片"),
        null=True,
        default=None,
        blank=True,
    )
    prod_quantity = models.PositiveIntegerField(default=0, verbose_name=_("商品數量"))
    prod_unit = models.PositiveSmallIntegerField(
        default=UnitChoices.INDIVIDUAL, choices=UnitChoices, verbose_name=_("商品單位")
    )

    prod_cate_no = models.ForeignKey(
        verbose_name=_("商品分類編號"),
        to=ProdCategory,
        on_delete=models.SET_NULL,
        null=True,
    )

    prod_effective_start_date = models.DateField(
        verbose_name=_("商品生效起日"),
        auto_now_add=True,
    )

    prod_effective_end_date = models.DateField(
        verbose_name=_("商品生效迄日"),
        default=timezone.make_aware(timezone.datetime(9999, 1, 1)),
    )

    prod_sales_status = models.PositiveSmallIntegerField(
        verbose_name=_("商品銷售狀態"),
        choices=SalesStatusChoices,
        default=SalesStatusChoices.NORMAL,
    )

    prod_quality_assurance_status = models.PositiveSmallIntegerField(
        verbose_name=_("商品品保狀態"),
        choices=QualityAssuranceStatusChoices,
        default=QualityAssuranceStatusChoices.NORMAL,
    )

    prod_cost_price = models.FloatField(verbose_name=_("商品成本價格"))

    prod_retail_price = models.FloatField(verbose_name=_("商品零售價格"))

    prod_sell_zone = models.CharField(max_length=1, verbose_name=_("商品銷售區域"))

    prod_outer_quantity = models.PositiveIntegerField(verbose_name=_("商品箱入數"))
    prod_inner_quantity = models.PositiveIntegerField(verbose_name=_("商品收縮數"))

    prod_mfr_id = models.ForeignKey(
        verbose_name=_("商品廠商 ID"),
        to=Manufacturer,
        on_delete=models.CASCADE,
        default=1,
    )

    def __str__(self) -> str:
        return str(self.prod_no) + " - " + self.prod_name

    def get_absolute_url(self):
        return reverse("prod_detail", kwargs={"pk": self.prod_no})

    class Meta:
        ordering = ["prod_no"]


class ProdRestriction(models.Model):
    pr_no = models.BigAutoField(primary_key=True, verbose_name=_("限制編號"))
    pr_prod_no = models.ForeignKey(
        verbose_name=_("商品限制編號"),
        to=Prod,
        on_delete=models.CASCADE,
    )
    pr_unit_price = models.PositiveBigIntegerField(
        verbose_name=_("商品限制單價"),
        default=0,
    )
    pr_as_case_quantity = models.PositiveIntegerField(
        verbose_name=_("商品限制成箱數"),
        default=0,
    )
    pr_effective_start_date = models.DateField(
        verbose_name=_("商品限制生效起日"), default=timezone.now
    )
    pr_effective_end_date = models.DateField(
        verbose_name=_("商品限制生效迄日"),
        default=timezone.make_aware(timezone.datetime(9999, 1, 1)),
    )

prod/forms.py
from re import findall
from typing import Any, Mapping

from dal import autocomplete
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.forms.widgets import ClearableFileInput
from django.utils.translation import gettext_lazy as _

from .models import Prod, ProdRestriction


def validate_query_str(query: str) -> None:
    colon_num = len(findall(":", query))
    res = findall(pattern=r"(name:|desc:|type:|status:)[a-zA-Z0-9]+", string=query)
    if len(res) is not colon_num:
        raise ValidationError(
            "Invalid format. The query string after the colon should only contain alphanumeric characters or numbers."
        )


class QueryForm(forms.Form):
    query = forms.CharField(
        label="query string",
        label_suffix="",
        max_length=255,
        widget=forms.TextInput,
        validators=[
            RegexValidator(
                regex=r"(name:|desc:|type:|status:)",
                message="Invalid format. It should start with 'name:', 'desc:', 'type:', or 'status:'. Do not place a space after the colon.",
            ),
            validate_query_str,
        ],
        required=False,
    )


class CustomFileInput(ClearableFileInput):
    template_name = "base_inputs/file_input.html"


class ProdCommonInfo(forms.ModelForm):
    class Meta:
        model = Prod
        fields = "__all__"
        widgets = {
            "prod_desc": forms.Textarea(attrs={"rows": 5}),
            "prod_img": CustomFileInput,
            "prod_cate_no": autocomplete.ModelSelect2(
                url="prod_all_cate_autocomplete",
                attrs={
                    "data-placeholder": _("輸入一個商品分類編號或是商品名稱"),
                },
            ),
            "prod_mfr_id": autocomplete.ListSelect2(
                url="mfr_autocomplete",
                attrs={
                    "data-placeholder": _("輸入一個廠商編號或是廠商名稱"),
                },
            ),
        }


class ProdCreateForm(forms.ModelForm):
    def __init__(self, mfrs, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        choices_list = [(mfr.pk, mfr.mfr_name) for mfr in mfrs]
        self.fields["prod_mfr_id"].choices = choices_list

    class Meta(ProdCommonInfo.Meta):
        pass


class ProdUpdateForm(ProdCreateForm):
    class Meta(ProdCommonInfo.Meta):
        pass


class ExcelTableCreateForm(forms.Form):
    table_template = f"""prod_no\tprod_name\tprod_desc\tprod_img\tprod_quantity\tprod_cate_no\tprod_sales_status\tprod_quality_assurance_status\tprod_mfr_id
855175\tAndrew Fields\tCandidate carry student not.\t/images/300_fzfQXUx.jpeg\t10\t000001\t0\t0\t1
855176\tAndrew Fields\tCandidate carry student not.\t/images/300_fzfQXUx.jpeg\t10\t000001\t0\t0\t1
855177\tAndrew Fields\tCandidate carry student not.\t/images/300_fzfQXUx.jpeg\t10\t000001\t0\t0\t1"""
    excel_table = forms.CharField(
        label="Product Create Table",
        required=True,
        widget=forms.Textarea(
            attrs={"class": "input-form", "placeholder": table_template}
        ),
    )


class ExcelTableUpdateForm(forms.Form):
    table_template = f"""prod_no	prod_quantity
855175	10
855176	20
855177	30"""
    excel_table = forms.CharField(
        label="Product Update Table",
        required=True,
        widget=forms.Textarea(
            attrs={"class": "input-form", "placeholder": table_template}
        ),
    )


class ProdRestrictionCreateForm(forms.ModelForm):
    class Meta:
        fields = "__all__"
        model = ProdRestriction
        widgets = {
            "pr_prod_no": autocomplete.ModelSelect2(url="prod_autocomplete"),
        }

prod/templates/prod_create.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2 class="page-title">新增商品</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {{ form | crispy }}
        <input type="submit" value="新增" class="btn btn-primary">
    </form>
{% endblock content %}
{% block nav %}
    <li class="nav-item">
        <a href="{% url 'prod_create_multiple' %}" class="nav-link">新增多個商品</a>
    </li>
{% endblock nav %}
{% block head %}
    {{ form.media }}
{% endblock head %}

prod/templates/prod_create_multiple.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% block head %}
    <script>{% include "prod_create_multiple.js" %}</script>
{% endblock head %}
{% block content %}
    {% comment %} TODO: add server side verification {% endcomment %}
    <h2 class="page-title">新增多個商品</h2>
    <form action="" method="post">
        {{ form | crispy }}
        <input id="btn_create"
               type="submit"
               value="新增"
               disabled
               class="btn btn-primary disabled">
    </form>
    <p id="output"></p>
{% endblock content %}
{% block nav %}
    <li class="nav-item">
        <a href="{% url 'prod_create' %}" class="nav-link">新增商品</a>
    </li>
{% endblock nav %}

prod/templates/prod_dashboard.html
{% extends "_base.html" %}
{% load django_tables2 %}
{% block content %}
    {% for table in tables %}
        <div class="container">{% render_table table %}</div>
    {% endfor %}
{% endblock content %}
{% block head %}
    {% include "prod_dashboard_head.html" %}
{% endblock head %}

prod/templates/prod_dashboard_head.html
{% load static %}
<script src="{% static 'js/d3.v7.min.js' %}"></script>
{{ prod_cate_data|json_script:"prod_cate_data" }}
<script type="module" src="{% static 'js/prod_dashboard.js' %}"></script>

prod/templates/prod_delete.html
{% extends "_base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="bg-slate-50 p-4 ">
        <h2>刪除產品</h2>
        <p class="mb-4 text-xl">確定刪除產品 "{{ prod.prod_name }}"?</p>
        <form action="" method="post">
            {% csrf_token %}
            <input type="button" class="btn btn-outline-primary" value="取消" onclick="window.history.back();">
            <input type="submit"
                   value="確定"
                   class="btn btn-danger" />
        </form>
    </div>
{% endblock content %}

prod/templates/prod_detail.html
{% extends "_base.html" %}
{% load widget_tweaks %}
{% block content %}
    <div class="card">
        <div class="card-header">{{ prod.prod_name }}</div>
        {% if prod.prod_img %}
            <img src="{{ prod.prod_img.url }}"
                 height="256px"
                 width="256px"
                 alt="Product Image"
                 class="card-img-top" />
        {% else %}
            {% include "include/prod_no_image.html" %}
        {% endif %}
        <ul class="list-group list-group-flush">
            <li class="list-group-item">類別: {{ prod.prod_cate_no }}</li>
            <li class="list-group-item">銷售狀態: {{ prod.get_prod_sales_status_display }}</li>
            <li class="list-group-item">品保狀態: {{ prod.get_prod_quality_assurance_status_display }}</li>
            <li class="list-group-item">生效日期: {{ prod.prod_effective_date }}</li>
            <li class="list-group-item">數量: {{ prod.prod_quantity }}</li>
        </ul>
        <div class="card-footer d-flex flex-row gap-2">
            <a href="{% url 'prod_update' prod.pk %}"><i class="bi-pencil-square fs-4"></i></a>
            <a href="{% url 'prod_create' %}"><i class="bi-plus-circle fs-4"></i></a>
            <a href="{% url 'prod_delete' prod.pk %}"><i class="bi-trash fs-4"></i></a>
        </div>
    </div>
{% endblock content %}

prod/templates/prod_list.html
{% extends "_base.html" %}
{% load django_tables2 %}
{% load crispy_forms_tags %}
{% block content %}
    {% if filter %}
        <div class="container mb-4">
            <form method="get" id="form_filter">
                {{ filter.form | crispy }}
                <input type="submit" value="篩選" class="btn btn-primary">
                <input type="reset" value="清除" class="btn btn-outline-secondary ">
            </form>
        </div>
    {% endif %}
    <div class="container">{% render_table table %}</div>
    <script>
    let form_filter = document.getElementById("form_filter");
    let btn_reset = form_filter.querySelector("input[type='reset']")
    let inputs = form_filter.querySelectorAll("input:not([type='submit']):not([type='reset'])");
    btn_reset.addEventListener("click", (e) => {
        e.preventDefault()
        for (let input of inputs)
        {
            input.value= ""
        }
    })
    </script>
{% endblock content %}
{% block nav %}
    <li class="nav-item">
        <a href="{% url 'prod_create' %}" class="nav-link">新增商品</a>
    </li>
{% endblock nav %}

prod/templates/prod_update.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h2 class="page-title">更新商品</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="更新" class="btn btn-primary" />
    </form>
{% endblock content %}
{% block head %}
    {{ form.media }}
{% endblock head %}

prod/templates/prod_update_multiple.html
{% extends "_base.html" %}
{% load django_tables2 %}
{% load crispy_forms_tags %}
{% block head %}
    <script>{% include "prod_update_multiple.js" %}</script>
{% endblock head %}
{% block content %}
    <h2 class="page-title">更新多個商品</h2>
        {% if filter %}
            <form action="" method="get" class="hidden">
                {{ filter.form | crispy }}
                <input id="btn_query" type="submit" class="btn btn-primary" value="篩選">
            </form>
        {% endif %}
        <form action="" method="post" class="mb-4">
            {{ form | crispy }}
            <input id="btn_update"
                   type="submit"
                   value="更新"
                   disabled
                   class="btn btn-primary disabled">
        </form>
        {% render_table table %}
{% endblock content %}